### ISSUE TITLE
CSS - Border-box ou content-box

### ISSUE THREAD

**Issue by brunorafaelleao** [brunorafaelleao/PraticasHMTLCSS#17]
#### A diferença entre eles:
A propriedade `box-sizing` em CSS define como o navegador deve calcular a largura e a altura de um elemento. Quando você define `box-sizing: border-box;`, está especificando que o padding e a borda do elemento devem ser incluídos na largura e altura totais do elemento.

### Comportamento Padrão (`content-box`)

Por padrão, o valor de `box-sizing` é `content-box`. Isso significa que o padding e a borda são adicionados à largura e altura especificadas do elemento. Por exemplo:

```css
/* Padrão: box-sizing: content-box; */
div {
  width: 100px;
  padding: 10px;
  border: 5px solid black;
}
```

Neste caso, a largura total do `div` será `100px (largura) + 20px (padding) + 10px (borda) = 130px`.

### Com `box-sizing: border-box`

Quando você define `box-sizing: border-box;`, o padding e a borda são incluídos na largura e altura especificadas. Por exemplo:

```css
div {
  box-sizing: border-box;
  width: 100px;
  padding: 10px;
  border: 5px solid black;
}
```

Neste caso, a largura total do `div` será exatamente `100px`, pois o padding e a borda são incluídos na largura especificada.
